2023-01-04 15:51:12,930 : DEBUG : Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
2023-01-04 15:51:13,057 : DEBUG : Creating converter from 7 to 5
2023-01-04 15:51:13,057 : DEBUG : Creating converter from 5 to 7
2023-01-04 15:51:13,058 : DEBUG : Creating converter from 7 to 5
2023-01-04 15:51:13,058 : DEBUG : Creating converter from 5 to 7
2023-01-04 15:51:13,774 : INFO : Started server process [637]
2023-01-04 15:51:13,774 : INFO : Waiting for application startup.
2023-01-04 15:51:13,775 : INFO : Application startup complete.
2023-01-04 15:52:33,813 : ERROR : Exception in ASGI application
Traceback (most recent call last):
  File "/home/leonardo/.local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/leonardo/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/leonardo/.local/lib/python3.8/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/home/leonardo/.local/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/leonardo/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/leonardo/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/leonardo/.local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/leonardo/.local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/home/leonardo/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/home/leonardo/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/home/leonardo/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/leonardo/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/leonardo/.local/lib/python3.8/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/home/leonardo/.local/lib/python3.8/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/home/leonardo/.local/lib/python3.8/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/leonardo/.local/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/home/leonardo/.local/lib/python3.8/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/leonardo/.local/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/leonardo/.local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/leonardo/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/leonardo/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/mnt/c/Users/leona/Desktop/PRETEST-SERVER/API-AutomationDocuments/./router/Secretaria.py", line 90, in secretarias_ingresar_al_sistema
    print(result[9])
TypeError: 'NoneType' object is not subscriptable
2023-01-04 15:53:15,294 : INFO : Se obtuvo informaci√≥n de todos los estudiantes
2023-01-04 15:54:17,433 : WARNING : Estudiante con el ID: 2 actualizado correctamente
2023-01-04 15:54:29,095 : INFO : Shutting down
2023-01-04 15:54:29,199 : INFO : Waiting for application shutdown.
2023-01-04 15:54:29,200 : INFO : Application shutdown complete.
2023-01-04 15:54:29,200 : INFO : Finished server process [637]
